---
- name: Deploy friends-app-frontend
  hosts: app-servers
  become: true
  become_user: "root"
  vars:
    image_tag: "{{ GIT_BRANCH|default('latest') }}"
    docker_repo: "753380798922.dkr.ecr.eu-central-1.amazonaws.com/friends-app/frontend"
    container_name: "frontend"
    docker_network_name: "friends-app-network"
  roles:
    - frontend
